const Data = [
  {
    id: 1,
    cityName: "Panaji",
    cityDetails: "Explore our city from beautiful beaches to historic architecture, fine dining, and vibrant markets.",
    projects: [
      {
        id: 1,
        status: "Ongoing",
        proectImage: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8YXBhcnRtZW50fGVufDB8fDB8fHww",
        proectname: "Buena Vista",
        projectadress: "West Panaji",
        projectdescript: "Modern 2BHK apartment with sea view.",
        projectbeds: 2,
        projectshowers: 2,
        proectarea: 1200,
        proectowner: "Mr. Bean",
        proectownerimage: "https://randomuser.me/api/portraits/men/45.jpg"
      },
      {
        id: 2,
        status: "Delivered",
        proectImage: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?q=80",
        proectname: "Sea Breeze Residency",
        projectadress: "East Panaji",
        projectdescript: "Luxury 3BHK with garden view.",
        projectbeds: 3,
        projectshowers: 3,
        proectarea: 1600,
        proectowner: "Ms. Patel",
        proectownerimage: "https://randomuser.me/api/portraits/women/65.jpg"
      },
      {
        id: 3,
        status: "Delivered",
        proectImage: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?q=80",
        proectname: "Sunset Towers",
        projectadress: "North Panaji",
        projectdescript: "Luxury apartments with city views.",
        projectbeds: 4,
        projectshowers: 3,
        proectarea: 2200,
        proectowner: "Mr. Naik",
        proectownerimage: "https://randomuser.me/api/portraits/men/30.jpg"
      },
      {
        id: 4,
        status: "Ongoing",
        proectImage: "https://images.unsplash.com/photo-1554995207-c18c203602cb?q=80",
        proectname: "Ocean Crest",
        projectadress: "Central Panaji",
        projectdescript: "Under-construction with oceanic theme.",
        projectbeds: 3,
        projectshowers: 2,
        proectarea: 1500,
        proectowner: "Ms. Gomes",
        proectownerimage: "https://randomuser.me/api/portraits/women/34.jpg"
      },
      {
        id: 16,
        status: "Ongoing",
        proectImage: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8YXBhcnRtZW50fGVufDB8fDB8fHww",
        proectname: "Coral Heights",
        projectadress: "South Panaji",
        projectdescript: "Premium 3BHK with rooftop amenities.",
        projectbeds: 3,
        projectshowers: 3,
        proectarea: 1800,
        proectowner: "Mr. Dias",
        proectownerimage: "https://randomuser.me/api/portraits/men/50.jpg"
      },
      {
        id: 17,
        status: "Delivered",
        proectImage: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80",
        proectname: "Marina Gardens",
        projectadress: "Panaji Waterfront",
        projectdescript: "Spacious 2BHK with marina views.",
        projectbeds: 2,
        projectshowers: 2,
        proectarea: 1300,
        proectowner: "Ms. Rodrigues",
        proectownerimage: "https://randomuser.me/api/portraits/women/20.jpg"
      },
      {
        id: 18,
        status: "Delivered",
        proectImage: "https://images.unsplash.com/photo-1582407947304-fd86f028f716?q=80",
        proectname: "Palm Residency",
        projectadress: "Panaji Heights",
        projectdescript: "Elegant apartments with modern facilities.",
        projectbeds: 3,
        projectshowers: 2,
        proectarea: 1700,
        proectowner: "Mr. Vaz",
        proectownerimage: "https://randomuser.me/api/portraits/men/35.jpg"
      }
    ]
  },
  {
    id: 2,
    cityName: "Mapusa",
    cityDetails: "Mapusa offers vibrant street life, traditional markets, and residential spaces close to nature and city life.",
    projects: [
      {
        id: 5,
        status: "Ongoing",
        proectImage: "https://images.unsplash.com/photo-1690987601363-83022d125159?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MzB8fGFwYXJ0bWVudHxlbnwwfHwwfHx8MA%3D%3D",
        proectname: "Green Valley",
        projectadress: "North Mapusa",
        projectdescript: "Elegant villas surrounded by greenery.",
        projectbeds: 4,
        projectshowers: 3,
        proectarea: 2500,
        proectowner: "Mr. Joshi",
        proectownerimage: "https://randomuser.me/api/portraits/men/32.jpg"
      },
      {
        id: 6,
        status: "Delivered",
        proectImage: "https://images.unsplash.com/photo-1572120360610-d971b9d7767c?q=80",
        proectname: "Mapusa Heights",
        projectadress: "Central Mapusa",
        projectdescript: "Affordable housing in heart of town.",
        projectbeds: 2,
        projectshowers: 2,
        proectarea: 1100,
        proectowner: "Ms. Mehta",
        proectownerimage: "https://randomuser.me/api/portraits/women/44.jpg"
      },
      {
        id: 7,
        status: "Delivered",
        proectImage: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?q=80",
        proectname: "Skyline Residency",
        projectadress: "East Mapusa",
        projectdescript: "2BHK apartments with hill view.",
        projectbeds: 2,
        projectshowers: 2,
        proectarea: 1000,
        proectowner: "Mr. Fernandes",
        proectownerimage: "https://randomuser.me/api/portraits/men/12.jpg"
      },
      {
        id: 19,
        status: "Ongoing",
        proectImage: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80",
        proectname: "Riverfront Villas",
        projectadress: "West Mapusa",
        projectdescript: "Luxury villas with river views.",
        projectbeds: 4,
        projectshowers: 4,
        proectarea: 2800,
        proectowner: "Ms. Lobo",
        proectownerimage: "https://randomuser.me/api/portraits/women/28.jpg"
      },
      {
        id: 20,
        status: "Ongoing",
        proectImage: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?q=80",
        proectname: "Mapusa Greens",
        projectadress: "South Mapusa",
        projectdescript: "Eco-friendly 3BHK apartments.",
        projectbeds: 3,
        projectshowers: 2,
        proectarea: 1400,
        proectowner: "Mr. Kulkarni",
        proectownerimage: "https://randomuser.me/api/portraits/men/38.jpg"
      },
      {
        id: 21,
        status: "Delivered",
        proectImage: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?q=80",
        proectname: "Hillside Homes",
        projectadress: "Mapusa Outskirts",
        projectdescript: "Spacious 3BHK with scenic views.",
        projectbeds: 3,
        projectshowers: 3,
        proectarea: 1600,
        proectowner: "Ms. Sharma",
        proectownerimage: "https://randomuser.me/api/portraits/women/15.jpg"
      },
      {
        id: 22,
        status: "Delivered",
        proectImage: "https://images.unsplash.com/photo-1554995207-c18c203602cb?q=80",
        proectname: "Market View Towers",
        projectadress: "Central Mapusa",
        projectdescript: "Modern apartments near markets.",
        projectbeds: 2,
        projectshowers: 2,
        proectarea: 1200,
        proectowner: "Mr. Desai",
        proectownerimage: "https://randomuser.me/api/portraits/men/22.jpg"
      }
    ]
  },
  {
    id: 3,
    cityName: "Margao",
    cityDetails: "Cultural hub of South Goa offering spacious homes, heritage surroundings, and close-knit communities.",
    projects: [
      {
        id: 8,
        status: "Delivered",
        proectImage: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80",
        proectname: "Heritage Homes",
        projectadress: "Old Margao",
        projectdescript: "Colonial-style villas with gardens.",
        projectbeds: 3,
        projectshowers: 3,
        proectarea: 1900,
        proectowner: "Ms. D’Souza",
        proectownerimage: "https://randomuser.me/api/portraits/women/50.jpg"
      },
      {
        id: 9,
        status: "Ongoing",
        proectImage: "https://images.unsplash.com/photo-1580041065738-e72023775cdc?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDR8fGFwYXJ0bWVudHxlbnwwfHwwfHx8MA%3D%3D",
        proectname: "Palm Grove",
        projectadress: "South Margao",
        projectdescript: "Modern 3BHK in gated society.",
        projectbeds: 3,
        projectshowers: 2,
        proectarea: 1400,
        proectowner: "Mr. Shetty",
        proectownerimage: "https://randomuser.me/api/portraits/men/25.jpg"
      },
      {
        id: 23,
        status: "Ongoing",
        proectImage: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80",
        proectname: "Margao Meadows",
        projectadress: "East Margao",
        projectdescript: "Premium apartments with lush greenery.",
        projectbeds: 3,
        projectshowers: 3,
        proectarea: 1700,
        proectowner: "Ms. Almeida",
        proectownerimage: "https://randomuser.me/api/portraits/women/30.jpg"
      },
      {
        id: 24,
        status: "Ongoing",
        proectImage: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?q=80",
        proectname: "Cityscape Towers",
        projectadress: "Central Margao",
        projectdescript: "High-rise with modern amenities.",
        projectbeds: 2,
        projectshowers: 2,
        proectarea: 1200,
        proectowner: "Mr. Pereira",
        proectownerimage: "https://randomuser.me/api/portraits/men/18.jpg"
      },
      {
        id: 25,
        status: "Delivered",
        proectImage: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?q=80",
        proectname: "Garden Residency",
        projectadress: "North Margao",
        projectdescript: "2BHK homes with garden access.",
        projectbeds: 2,
        projectshowers: 2,
        proectarea: 1100,
        proectowner: "Ms. Naik",
        proectownerimage: "https://randomuser.me/api/portraits/women/25.jpg"
      },
      {
        id: 26,
        status: "Delivered",
        proectImage: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?q=80",
        proectname: "Heritage Plaza",
        projectadress: "Margao Center",
        projectdescript: "Luxury apartments with heritage charm.",
        projectbeds: 3,
        projectshowers: 3,
        proectarea: 1800,
        proectowner: "Mr. Costa",
        proectownerimage: "https://randomuser.me/api/portraits/men/33.jpg"
      },
      {
        id: 27,
        status: "Delivered",
        proectImage: "https://images.unsplash.com/photo-1554995207-c18c203602cb?q=80",
        proectname: "Sunrise Villas",
        projectadress: "West Margao",
        projectdescript: "Spacious villas with modern design.",
        projectbeds: 4,
        projectshowers: 3,
        proectarea: 2200,
        proectowner: "Ms. Menezes",
        proectownerimage: "https://randomuser.me/api/portraits/women/18.jpg"
      }
    ]
  },
  {
    id: 4,
    cityName: "Vasco-da-Gama",
    cityDetails: "Strategic port city with affordable flats and new apartment complexes near beaches and airport.",
    projects: [
      {
        id: 10,
        status: "Delivered",
        proectImage: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?q=80",
        proectname: "Portview Apartments",
        projectadress: "Harbor Road",
        projectdescript: "2BHK apartments with sea breeze.",
        projectbeds: 2,
        projectshowers: 2,
        proectarea: 1050,
        proectowner: "Ms. Pinto",
        proectownerimage: "https://randomuser.me/api/portraits/women/33.jpg"
      },
      {
        id: 11,
        status: "Ongoing",
        proectImage: "https://images.unsplash.com/photo-1580041065738-e72023775cdc?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDR8fGFwYXJ0bWVudHxlbnwwfHwwfHx8MA%3D%3D",
        proectname: "Sea Pearl",
        projectadress: "Airport Road",
        projectdescript: "New project under premium class.",
        projectbeds: 3,
        projectshowers: 3,
        proectarea: 1600,
        proectowner: "Mr. Rao",
        proectownerimage: "https://randomuser.me/api/portraits/men/40.jpg"
      },
      {
        id: 28,
        status: "Ongoing",
        proectImage: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80",
        proectname: "Harbor Heights",
        projectadress: "Vasco Coast",
        projectdescript: "Modern 3BHK with coastal views.",
        projectbeds: 3,
        projectshowers: 2,
        proectarea: 1500,
        proectowner: "Ms. Fernandes",
        proectownerimage: "https://randomuser.me/api/portraits/women/40.jpg"
      },
      {
        id: 29,
        status: "Ongoing",
        proectImage: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?q=80",
        proectname: "Skyport Residency",
        projectadress: "Near Airport",
        projectdescript: "High-rise with airport proximity.",
        projectbeds: 2,
        projectshowers: 2,
        proectarea: 1200,
        proectowner: "Mr. D’Costa",
        proectownerimage: "https://randomuser.me/api/portraits/men/20.jpg"
      },
      {
        id: 30,
        status: "Delivered",
        proectImage: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?q=80",
        proectname: "Coastal Towers",
        projectadress: "Vasco Beachfront",
        projectdescript: "Luxury 2BHK with sea views.",
        projectbeds: 2,
        projectshowers: 2,
        proectarea: 1100,
        proectowner: "Ms. Vaz",
        proectownerimage: "https://randomuser.me/api/portraits/women/35.jpg"
      },
      {
        id: 31,
        status: "Delivered",
        proectImage: "https://images.unsplash.com/photo-1554995207-c18c203602cb?q=80",
        proectname: "Marina Flats",
        projectadress: "Vasco Harbor",
        projectdescript: "Affordable 2BHK apartments.",
        projectbeds: 2,
        projectshowers: 1,
        proectarea: 950,
        proectowner: "Mr. Gonsalves",
        proectownerimage: "https://randomuser.me/api/portraits/men/28.jpg"
      },
      {
        id: 32,
        status: "Delivered",
        proectImage: "https://images.unsplash.com/photo-1560448075-bb0bfcf7c13a?q=80",
        proectname: "Seaside Homes",
        projectadress: "Vasco West",
        projectdescript: "Modern apartments with sea access.",
        projectbeds: 3,
        projectshowers: 2,
        proectarea: 1400,
        proectowner: "Ms. Lobo",
        proectownerimage: "https://randomuser.me/api/portraits/women/22.jpg"
      }
    ]
  },
  {
    id: 5,
    cityName: "Calangute",
    cityDetails: "Tourist hotspot with lavish resorts, apartments, and cozy residential complexes near the beach.",
    projects: [
      {
        id: 12,
        status: "Delivered",
        proectImage: "https://images.unsplash.com/photo-1582407947304-fd86f028f716?q=80",
        proectname: "Beachfront Residency",
        projectadress: "Calangute Main",
        projectdescript: "Seaside living with 5-star comfort.",
        projectbeds: 3,
        projectshowers: 2,
        proectarea: 1350,
        proectowner: "Ms. Pereira",
        proectownerimage: "https://randomuser.me/api/portraits/women/22.jpg"
      },
      {
        id: 33,
        status: "Ongoing",
        proectImage: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80",
        proectname: "Sunset Shores",
        projectadress: "Calangute Beach",
        projectdescript: "Luxury villas with beach access.",
        projectbeds: 4,
        projectshowers: 4,
        proectarea: 2500,
        proectowner: "Mr. D’Silva",
        proectownerimage: "https://randomuser.me/api/portraits/men/45.jpg"
      },
      {
        id: 34,
        status: "Ongoing",
        proectImage: "https://images.unsplash.com/photo-1580041065738-e72023775cdc?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDR8fGFwYXJ0bWVudHxlbnwwfHwwfHx8MA%3D%3D",
        proectname: "Ocean Waves",
        projectadress: "North Calangute",
        projectdescript: "Modern 3BHK with ocean views.",
        projectbeds: 3,
        projectshowers: 3,
        proectarea: 1800,
        proectowner: "Ms. Miranda",
        proectownerimage: "https://randomuser.me/api/portraits/women/28.jpg"
      },
      {
        id: 35,
        status: "Ongoing",
        proectImage: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?q=80",
        proectname: "Coral Sands",
        projectadress: "South Calangute",
        projectdescript: "Premium apartments under construction.",
        projectbeds: 2,
        projectshowers: 2,
        proectarea: 1200,
        proectowner: "Mr. Almeida",
        proectownerimage: "https://randomuser.me/api/portraits/men/30.jpg"
      },
      {
        id: 36,
        status: "Delivered",
        proectImage: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?q=80",
        proectname: "Tropical Towers",
        projectadress: "Calangute Center",
        projectdescript: "Luxury 2BHK with resort amenities.",
        projectbeds: 2,
        projectshowers: 2,
        proectarea: 1100,
        proectowner: "Ms. Costa",
        proectownerimage: "https://randomuser.me/api/portraits/women/15.jpg"
      },
      {
        id: 37,
        status: "Delivered",
        proectImage: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?q=80",
        proectname: "Seaside Villas",
        projectadress: "Calangute Beach Road",
        projectdescript: "Spacious villas with beach proximity.",
        projectbeds: 3,
        projectshowers: 3,
        proectarea: 1600,
        proectowner: "Mr. Fernandes",
        proectownerimage: "https://randomuser.me/api/portraits/men/20.jpg"
      },
      {
        id: 38,
        status: "Delivered",
        proectImage: "https://images.unsplash.com/photo-1554995207-c18c203602cb?q=80",
        proectname: "Sunset Plaza",
        projectadress: "West Calangute",
        projectdescript: "Modern apartments with sunset views.",
        projectbeds: 2,
        projectshowers: 2,
        proectarea: 1300,
        proectowner: "Ms. D’Souza",
        proectownerimage: "https://randomuser.me/api/portraits/women/30.jpg"
      }
    ]
  },
  {
    id: 6,
    cityName: "Candolim",
    cityDetails: "Upscale town with premium villas, luxury apartments, and beach proximity.",
    projects: [
      {
        id: 13,
        status: "Ongoing",
        proectImage: "https://images.unsplash.com/photo-1487958449943-2429e8be8625?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDJ8fGJ1aWxkaW5nfGVufDB8fDB8fHww",
        proectname: "Golden Dunes",
        projectadress: "Candolim Beach Road",
        projectdescript: "Luxurious beach villas under construction.",
        projectbeds: 4,
        projectshowers: 4,
        proectarea: 3000,
        proectowner: "Mr. Almeida",
        proectownerimage: "https://randomuser.me/api/portraits/men/28.jpg"
      },
      {
        id: 39,
        status: "Ongoing",
        proectImage: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80",
        proectname: "Sunrise Villas",
        projectadress: "North Candolim",
        projectdescript: "Premium villas with modern amenities.",
        projectbeds: 4,
        projectshowers: 4,
        proectarea: 2800,
        proectowner: "Ms. Pereira",
        proectownerimage: "https://randomuser.me/api/portraits/women/25.jpg"
      },
      {
        id: 40,
        status: "Ongoing",
        proectImage: "https://images.unsplash.com/photo-1580041065738-e72023775cdc?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDR8fGFwYXJ0bWVudHxlbnwwfHwwfHx8MA%3D%3D",
        proectname: "Beachside Towers",
        projectadress: "Candolim Coast",
        projectdescript: "High-rise with beachfront views.",
        projectbeds: 3,
        projectshowers: 3,
        proectarea: 1800,
        proectowner: "Mr. Vaz",
        proectownerimage: "https://randomuser.me/api/portraits/men/35.jpg"
      },
      {
        id: 41,
        status: "Delivered",
        proectImage: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?q=80",
        proectname: "Oceanfront Residency",
        projectadress: "Central Candolim",
        projectdescript: "Luxury 3BHK with ocean access.",
        projectbeds: 3,
        projectshowers: 3,
        proectarea: 1700,
        proectowner: "Ms. Lobo",
        proectownerimage: "https://randomuser.me/api/portraits/women/20.jpg"
      },
      {
        id: 42,
        status: "Delivered",
        proectImage: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?q=80",
        proectname: "Candolim Heights",
        projectadress: "South Candolim",
        projectdescript: "Modern apartments with beach proximity.",
        projectbeds: 2,
        projectshowers: 2,
        proectarea: 1200,
        proectowner: "Mr. Fernandes",
        proectownerimage: "https://randomuser.me/api/portraits/men/22.jpg"
      },
      {
        id: 43,
        status: "Delivered",
        proectImage: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?q=80",
        proectname: "Sunset Dunes",
        projectadress: "Candolim Beach",
        projectdescript: "Luxury villas with sunset views.",
        projectbeds: 4,
        projectshowers: 3,
        proectarea: 2500,
        proectowner: "Ms. D’Costa",
        proectownerimage: "https://randomuser.me/api/portraits/women/28.jpg"
      },
      {
        id: 44,
        status: "Delivered",
        proectImage: "https://images.unsplash.com/photo-1554995207-c18c203602cb?q=80",
        proectname: "Coastal Plaza",
        projectadress: "West Candolim",
        projectdescript: "Premium 2BHK apartments.",
        projectbeds: 2,
        projectshowers: 2,
        proectarea: 1100,
        proectowner: "Mr. Gonsalves",
        proectownerimage: "https://randomuser.me/api/portraits/men/30.jpg"
      }
    ]
  },
  {
    id: 7,
    cityName: "Ponda",
    cityDetails: "Culturally rich area with quiet neighborhoods and religious sites, perfect for peaceful living.",
    projects: [
      {
        id: 14,
        status: "Delivered",
        proectImage: "https://images.unsplash.com/photo-1522156373667-4c7234bbd804?q=80",
        proectname: "Temple View Apartments",
        projectadress: "Central Ponda",
        projectdescript: "2BHK apartments with temple views.",
        projectbeds: 2,
        projectshowers: 2,
        proectarea: 950,
        proectowner: "Ms. Naidu",
        proectownerimage: "https://randomuser.me/api/portraits/women/10.jpg"
      },
      {
        id: 45,
        status: "Ongoing",
        proectImage: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80",
        proectname: "Serenity Homes",
        projectadress: "North Ponda",
        projectdescript: "Modern 3BHK with peaceful surroundings.",
        projectbeds: 3,
        projectshowers: 2,
        proectarea: 1400,
        proectowner: "Mr. Sharma",
        proectownerimage: "https://randomuser.me/api/portraits/men/25.jpg"
      },
      {
        id: 46,
        status: "Ongoing",
        proectImage: "https://images.unsplash.com/photo-1580041065738-e72023775cdc?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDR8fGFwYXJ0bWVudHxlbnwwfHwwfHx8MA%3D%3D",
        proectname: "Ponda Greens",
        projectadress: "East Ponda",
        projectdescript: "Eco-friendly apartments under construction.",
        projectbeds: 2,
        projectshowers: 2,
        proectarea: 1100,
        proectowner: "Ms. Desai",
        proectownerimage: "https://randomuser.me/api/portraits/women/22.jpg"
      },
      {
        id: 47,
        status: "Ongoing",
        proectImage: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?q=80",
        proectname: "Sacred Residency",
        projectadress: "South Ponda",
        projectdescript: "Spacious 3BHK near religious sites.",
        projectbeds: 3,
        projectshowers: 3,
        proectarea: 1600,
        proectowner: "Mr. Kulkarni",
        proectownerimage: "https://randomuser.me/api/portraits/men/20.jpg"
      },
      {
        id: 48,
        status: "Delivered",
        proectImage: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?q=80",
        proectname: "Peaceful Towers",
        projectadress: "West Ponda",
        projectdescript: "Affordable 2BHK with serene views.",
        projectbeds: 2,
        projectshowers: 1,
        proectarea: 900,
        proectowner: "Ms. Almeida",
        proectownerimage: "https://randomuser.me/api/portraits/women/30.jpg"
      },
      {
        id: 49,
        status: "Delivered",
        proectImage: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?q=80",
        proectname: "Harmony Flats",
        projectadress: "Ponda Center",
        projectdescript: "Modern apartments with temple proximity.",
        projectbeds: 2,
        projectshowers: 2,
        proectarea: 1000,
        proectowner: "Mr. Naik",
        proectownerimage: "https://randomuser.me/api/portraits/men/28.jpg"
      },
      {
        id: 50,
        status: "Delivered",
        proectImage: "https://images.unsplash.com/photo-1554995207-c18c203602cb?q=80",
        proectname: "Ponda Heights",
        projectadress: "North Ponda",
        projectdescript: "Spacious 3BHK with modern amenities.",
        projectbeds: 3,
        projectshowers: 2,
        proectarea: 1400,
        proectowner: "Ms. Pereira",
        proectownerimage: "https://randomuser.me/api/portraits/women/25.jpg"
      }
    ]
  },
  {
    id: 8,
    cityName: "Bicholim",
    cityDetails: "Hill town with scenic beauty and affordable residential developments ideal for families and retirees.",
    projects: [
      {
        id: 15,
        status: "Ongoing",
        proectImage: "https://images.unsplash.com/photo-1582407947304-fd86f028f716?q=80",
        proectname: "Hilltop Residency",
        projectadress: "Bicholim West",
        projectdescript: "Budget-friendly flats with great views.",
        projectbeds: 2,
        projectshowers: 1,
        proectarea: 900,
        proectowner: "Mr. Sawant",
        proectownerimage: "https://randomuser.me/api/portraits/men/15.jpg"
      },
      {
        id: 51,
        status: "Ongoing",
        proectImage: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80",
        proectname: "Hillside Villas",
        projectadress: "North Bicholim",
        projectdescript: "Spacious villas with hill views.",
        projectbeds: 3,
        projectshowers: 2,
        proectarea: 1500,
        proectowner: "Ms. Fernandes",
        proectownerimage: "https://randomuser.me/api/portraits/women/20.jpg"
      },
      {
        id: 52,
        status: "Ongoing",
        proectImage: "https://images.unsplash.com/photo-1580041065738-e72023775cdc?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDR8fGFwYXJ0bWVudHxlbnwwfHwwfHx8MA%3D%3D",
        proectname: "Green Hills",
        projectadress: "East Bicholim",
        projectdescript: "Eco-friendly 2BHK apartments.",
        projectbeds: 2,
        projectshowers: 2,
        proectarea: 1100,
        proectowner: "Mr. Desai",
        proectownerimage: "https://randomuser.me/api/portraits/men/22.jpg"
      },
      {
        id: 53,
        status: "Delivered",
        proectImage: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?q=80",
        proectname: "Valley View Flats",
        projectadress: "South Bicholim",
        projectdescript: "Affordable apartments with scenic views.",
        projectbeds: 2,
        projectshowers: 1,
        proectarea: 950,
        proectowner: "Ms. Naik",
        proectownerimage: "https://randomuser.me/api/portraits/women/28.jpg"
      },
      {
        id: 54,
        status: "Delivered",
        proectImage: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?q=80",
        proectname: "Bicholim Towers",
        projectadress: "Central Bicholim",
        projectdescript: "Modern 2BHK with hill proximity.",
        projectbeds: 2,
        projectshowers: 2,
        proectarea: 1000,
        proectowner: "Mr. Kulkarni",
        proectownerimage: "https://randomuser.me/api/portraits/men/25.jpg"
      },
      {
        id: 55,
        status: "Delivered",
        proectImage: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?q=80",
        proectname: "Sunset Hills",
        projectadress: "West Bicholim",
        projectdescript: "Spacious 3BHK with modern design.",
        projectbeds: 3,
        projectshowers: 2,
        proectarea: 1400,
        proectowner: "Ms. Almeida",
        proectownerimage: "https://randomuser.me/api/portraits/women/22.jpg"
      },
      {
        id: 56,
        status: "Delivered",
        proectImage: "https://images.unsplash.com/photo-1554995207-c18c203602cb?q=80",
        proectname: "Hillview Residency",
        projectadress: "North Bicholim",
        projectdescript: "Affordable apartments with hill views.",
        projectbeds: 2,
        projectshowers: 1,
        proectarea: 900,
        proectowner: "Mr. Pereira",
        proectownerimage: "https://randomuser.me/api/portraits/men/20.jpg"
      }
    ]
  }
];

export default Data